language: node_js
sudo: false
os:
  - linux
  # - osx
  # Disabled during Mac builds outage:
  # https://www.traviscistatus.com/

node_js:
  - 9
  - 8
  - 6
  - 4

cache:
  directories:
    - ~/.npm

matrix:
  include:
    - node_js: 9
      env: HARMONY=true
