language: node_js
sudo: false
os:
  - linux
  # - osx
  # Disabled during Mac builds outage:
  # https://www.traviscistatus.com/

node_js:
  - 10
  - 8
  - 6

cache:
  directories:
    - ~/.npm

matrix:
  include:
    - node_js: 10
      env: HARMONY=true
