language: node_js
sudo: false
os:
  - linux
  - osx

node_js:
  - 10
  - 8
  - 6

cache:
  directories:
    - ~/.npm

matrix:
  include:
    - node_js: 10
      env: HARMONY=true

before_install:
  - npm i -g npm
